export const experiences = [
  {
    title: "Software Engineer",
    company: "SSingularitee Technologies Pvt Ltd",
    duration: "July 2024 - Present",
    technologies: [
      "JavaScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "Authjs",
      "Prisma",
      "OpenAI",
      "Gemini",
      "Python",
      "FastAPI",
      "Node.js",
      "PostgreSQL",
      "Redis",
      "Docker",
      "DigitalOcean",
    ],
    achievements: [
      "Leading the development of [OutCallerAI](https://outcallerai.com) — AI-powered outbound & inbound calling platform that automates multilingual lead qualification and follow-ups, boosting conversion efficiency.",
      "Built a live energy monitoring and analytics system using `Next.js`, `WebSockets` and `InfluxDB` to display real-time and historical data, implemented `GitHub Actions` for `CI/CD`.",
      "_RPA for Healthcare_ - Automated data workflows across 7+ healthcare platforms using `Selenium` and `FastAPI`, leading a team of 5 developers to reduce manual input for nurses and doctors.",
      "Integrated `WhatsApp Business` and `Gmail APIs` to enable seamless _calendar bookings_ and _multi-channel communication_ within [OutCallerAI](https://outcallerai.com)",
      "Designed and deployed scalable APIs using `FastAPI` and `Redis` queues to support _background job processing_ and _high-throughput workflows_.",
      "Implemented robust authentication and access control with `Auth.js`, `Prisma`, and `PostgreSQL`; containerized services with `Docker` and deployed to `DigitalOcean` for reliability and scalability.",
    ],
  },
  {
    title: "Web Developer Intern",
    company: "SSingularity Technologies",
    duration: "January 2023 - July 2023",
    technologies: [
      "JavaScript",
      "Laravel",
      "MySQL",
      "Bootstrap",
      "React Native",
      "React.js",
      "Chart.js",
    ],
    achievements: [
      "Enhanced website responsiveness and performance by optimizing `React.js` components and implementing adaptive layouts using `Bootstrap` and `Chart.js`",
      "Developed backend modules and RESTful APIs using `Laravel` and `MySQL`, improving data management and performance across multiple applications.",
      "Built a mobile application using `React Native`",
    ],
  },
];

export const education = [
  {
    degree: "B.E in Computer Engineering",
    institution: "KC College of Engineering",
    duration: "2022 - 2024",
    grade: "8.8/10",
  },
  {
    degree: "Diploma in Computer Engineering",
    institution: "K.J Somaiya Polytechnic",
    duration: "2018 - 2021",
    grade: "93%/100",
  },
];

export const skillCategories = {
  Frontend: [
    "JavaScript",
    "TypeScript",
    "React.js",
    "Next.js",
    "React Native",
    "Expo",
    "Electron",
    "Swift",
    "Motion",
    "Tailwind",
  ],
  Backend: ["Python", "FastAPI", "Node.js", "Express.js"],
  Database: [
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Upstash",
    "Neon",
    "Supabase",
    "Prisma",
    "Drizzle",
  ],
  DevOps: [
    "Docker",
    "DigitalOcean",
    "Cloudflare",
    "Vercel",
  ],
  "Tools / API's": [
    "OpenAI",
    "Gemini",
    "Resend",
    "Authjs",
    "BetterAuth",
    "Stripe",
    "GitHub",
    "VsCode",
    "Ghostty",
    "Postman",
    "Posthog",
    "Pnpm",
  ],
};
