export const experiences = [
  {
    title: "Software Engineer",
    company: "SSingularitee Technologies Pvt Ltd",
    duration: "July 2024 - Present",
    technologies: [
      "JavaScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "Authjs",
      "Prisma",
      "OpenAI",
      "Gemini",
      "Python",
      "FastAPI",
      "Node.js",
      "PostgreSQL",
      "Redis",
      "Docker",
      "DigitalOcean",
    ],
    achievements: [
      "Led the development of OutCallerAI, an AI-powered outbound calling platform that automates lead qualification and follow-ups in multiple languages, significantly improving conversion rates.",
      "Built OutRiskAI, an AI tool that analyzes legal risks, summarizes complex contracts, and facilitates communication with real lawyers—streamlining the legal review process for users.",
      "Engineered a live energy monitoring and analytics system using Next.js, WebSockets and InfluxDB to display real-time and historical data, implemented GitHub Actions for CI/CD.",
      "Automated data entry workflows for 7 different healthcare platforms used by nurses and doctors using RPA with Selenium and FastAPI, led a team of 5 developers on one major automation module.",
      "Integrated WhatsApp Business and Gmail APIs to enable seamless calendar bookings and multi-channel communication within customer-facing applications.",
      "Designed scalable and asynchronous APIs using FastAPI and Redis to handle real-time task processing.",
      "Implemented secure authentication, access control, and data models using Auth.js, Prisma and Postgres, with Dockerized deployments hosted on DigitalOcean for scalable and maintainable cloud infrastructure.",
    ],
  },
  {
    title: "Web Developer Intern",
    company: "SSingularity Technologies",
    duration: "January 2023 - July 2023",
    technologies: [
      "JavaScript",
      "Laravel",
      "MySQL",
      "Bootstrap",
      "React Native",
    ],
    achievements: [
      "Improved website performance through component optimization",
      "Implemented responsive layouts using Bootstrap",
      "Developed and maintained backend using Laravel and MySQL",
      "Developed mobile app using React Native",
    ],
  },
];

export const education = [
  {
    degree: "B.E in Computer Engineering",
    institution: "KC College of Engineering",
    duration: "2022 - 2024",
    grade: "8.8/10",
  },
  {
    degree: "Diploma in Computer Engineering",
    institution: "K.J Somaiya Polytechnic",
    duration: "2018 - 2021",
    grade: "93%/100",
  },
];

export const skillCategories = {
  Frontend: [
    "JavaScript",
    "TypeScript",
    "React.js",
    "Next.js",
    "React Native",
    "Expo",
    "Shadcn",
    "Motion",
    "Tailwind",
    "Sass",
    "Bootstrap",
  ],
  Backend: ["Python", "Node.js", "Express.js", "FastAPI"],
  Database: [
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Neon",
    "Supabase",
    "Prisma",
    "Drizzle",
  ],
  DevOps: ["Docker", "DigitalOcean", "Vercel", "Render"],
  Tools: [
    "OpenAI",
    "Gemini",
    "Authjs",
    "Clerk",
    "VsCode",
    "Git",
    "Warp",
    "Pnpm",
    "Postman",
    "Posthog",
  ],
};
