export const experiences = [
  {
    title: "Software Engineer",
    company: "SSingularitee Technologies Pvt Ltd",
    duration: "July 2024 - Present",
    technologies: [
      "JavaScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "Authjs",
      "Prisma",
      "OpenAI",
      "Gemini",
      "Python",
      "FastAPI",
      "Node.js",
      "PostgreSQL",
      "Redis",
      "Docker",
      "DigitalOcean",
    ],
    achievements: [
      "Built [OutCallerAI](https://outcallerai.com) — Led development of an AI-powered _outbound calling platform_ that automates multilingual lead qualification and follow-ups, boosting conversion efficiency.",
      "Developed [OutRiskAI](https://outriskai.com) — Engineered a legal AI assistant that _summarizes contracts_, _highlights risks_, and _connects users with real lawyers_ to streamline contract review workflows.",
      "Built a live energy monitoring and analytics system using `Next.js`, `WebSockets` and `InfluxDB` to display real-time and historical data, implemented `GitHub Actions` for `CI/CD`.",
      "_RPA for Healthcare_ - Automated data workflows across 7+ healthcare platforms using `Selenium` and `FastAPI`, leading a team of 5 developers to reduce manual input for nurses and doctors.",
      "Integrated `WhatsApp Business` and `Gmail APIs` to enable seamless _calendar bookings_ and _multi-channel communication_ within [OutCallerAI](https://outcallerai.com)",
      "Designed and deployed scalable APIs using `FastAPI` and `Redis` queues to support _background job processing_ and _high-throughput workflows_.",
      "Implemented robust authentication and access control with `Auth.js`, `Prisma`, and `PostgreSQL`; containerized services with `Docker` and deployed to `DigitalOcean` for reliability and scalability.",
    ],
  },
  {
    title: "Web Developer Intern",
    company: "SSingularity Technologies",
    duration: "January 2023 - July 2023",
    technologies: [
      "JavaScript",
      "Laravel",
      "MySQL",
      "Bootstrap",
      "React Native",
      "React.js",
      "Chart.js",
    ],
    achievements: [
      "Enhanced website responsiveness and performance by optimizing `React.js` components and implementing adaptive layouts using `Bootstrap` and `Chart.js`",
      "Developed backend modules and RESTful APIs using `Laravel` and `MySQL`, improving data management and performance across multiple applications.",
      "Built a mobile application using `React Native`",
    ],
  },
];

export const education = [
  {
    degree: "B.E in Computer Engineering",
    institution: "KC College of Engineering",
    duration: "2022 - 2024",
    grade: "8.8/10",
  },
  {
    degree: "Diploma in Computer Engineering",
    institution: "K.J Somaiya Polytechnic",
    duration: "2018 - 2021",
    grade: "93%/100",
  },
];

export const skillCategories = {
  Frontend: [
    "JavaScript",
    "TypeScript",
    "React.js",
    "Next.js",
    "React Native",
    "Expo",
    "Shadcn",
    "Motion",
    "Tailwind",
    "Sass",
    "Bootstrap",
  ],
  Backend: ["Python", "Node.js", "Express.js", "FastAPI"],
  Database: [
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Neon",
    "Supabase",
    "Prisma",
    "Drizzle",
  ],
  DevOps: ["Docker", "DigitalOcean", "Vercel", "Render"],
  Tools: [
    "OpenAI",
    "Gemini",
    "Authjs",
    "Clerk",
    "VsCode",
    "Git",
    "Warp",
    "Pnpm",
    "Postman",
    "Posthog",
  ],
};
