export const projects = [
  {
    id: "outcallerai",
    title: "OutCallerAI",
    description:
      "AI-powered outbound caller that pre-qualifies real estate leads with life-like conversations.",
    tags: [
      "JavaScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "Authjs",
      "Prisma",
      "OpenAI",
      "Python",
      "FastAPI",
      "PostgreSQL",
      "Docker",
      "DigitalOcean",
      // "Plivo",
    ],
    deployedUrl: "https://outcallerai.com",
    imageUrl: "/projects/outcallerai.png",
  },
  {
    id: "outriskai",
    title: "OutRiskAI",
    description:
      "AI tool to analyze legal risk, summarize contracts, and connect with real lawyers.",
    tags: [
      "JavaScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "Authjs",
      "Prisma",
      "OpenAI",
      "Python",
      "FastAPI",
      "Node.js",
      "PostgreSQL",
      "Docker",
      "DigitalOcean",
    ],
    deployedUrl: "https://outriskai.com",
    imageUrl: "/projects/outriskai.png",
  },
  {
    id: "hypeitup",
    title: "HypeItUp",
    description:
      "No-code platform to build waitlists, collect signups, and track analytics in real-time.",
    tags: [
      "JavaScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "Prisma",
      "PostgreSQL",
      "Neon",
      "Docker",
      // "Vercel",
      // "Clerk",
      // "Uploadthing",
    ],
    deployedUrl: "https://hypeitup.me",
    imageUrl: "/projects/hypeitup.png",
  },
  {
    id: "devfinder",
    title: "DevFinder",
    description:
      "Developer networking platform to connect, collaborate on projects, and share knowledge",
    tags: [
      "TypeScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "Authjs",
      "Drizzle",
      "PostgreSQL",
      "Docker",
      // "Stream SDK",
    ],
    githubUrl: "https://github.com/FALAK097/devfinder",
    imageUrl: "/projects/devfinder.png",
  },
];
