export const projects = [
  {
    id: "outcallerai",
    title: "OutCallerAI",
    description:
      "AI-powered outbound caller that pre-qualifies leads with life-like conversations.",
    tags: [
      "JavaScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "Authjs",
      "Prisma",
      "OpenAI",
      "Gemini",
      "Python",
      "FastAPI",
      "PostgreSQL",
      "Redis",
      "Docker",
      "DigitalOcean",
      // "Plivo",
    ],
    deployedUrl: "https://outcallerai.com",
    imageUrl: "/projects/outcallerai.png",
  },
  {
    id: "outriskai",
    title: "OutRiskAI",
    description:
      "AI tool to analyze legal risk, summarize contracts, and connect with real lawyers.",
    tags: [
      "JavaScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "Authjs",
      "Prisma",
      "OpenAI",
      "Gemini",
      "Python",
      "FastAPI",
      "Node.js",
      "PostgreSQL",
      "Docker",
      "DigitalOcean",
    ],
    deployedUrl: "https://outriskai.com",
    imageUrl: "/projects/outriskai.png",
  },
  {
    id: "waitlyze",
    title: "Waitlyze",
    description:
      "No-code platform to build waitlists, collect signups, and track analytics in real-time.",
    tags: [
      "JavaScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "Prisma",
      "PostgreSQL",
      "Neon",
      "Docker",
      "Vercel",
      "Clerk",
      // "Uploadthing",
    ],
    deployedUrl:
      "https://waitlyze.falakgala.dev",
    imageUrl: "/projects/waitlyze.png",
  },
  {
    id: "devfinder",
    title: "DevFinder",
    description:
      "Developer networking platform to connect, collaborate on projects, and share knowledge",
    tags: [
      "TypeScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "Authjs",
      "Drizzle",
      "PostgreSQL",
      "Docker",
      // "Stream SDK",
    ],
    githubUrl: "https://github.com/FALAK097/devfinder",
    imageUrl: "/projects/devfinder.png",
  },
  {
    id: "spotify-clone",
    title: "Spotify Clone",
    description:
      "A full-stack music streaming web app replicating core Spotify features like playback, playlists, and user authentication.",
    tags: [
      "TypeScript",
      "React.js",
      "Next.js",
      "Tailwind CSS",
      "Supabase",
      "PostgreSQL",
      "Stripe",
      "Vercel",
    ],
    githubUrl: "https://github.com/FALAK097/spotify_clone",
    imageUrl: "/projects/spotify-clone.png",
  },
  {
    id: "mern-github",
    title: "MERN GitHub Viewer",
    description:
      "A GitHub profile viewer built with the MERN stack that displays user info, repositories, and followers.",
    tags: [
      "JavaScript",
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind",
      "GitHub API",
      "Render",
    ],
    deployedUrl: "https://mern-github.onrender.com",
    githubUrl: "https://github.com/FALAK097/mern-github",
    imageUrl: "/projects/mern-github.png",
  },
  {
    id: "codetoimage",
    title: "CodeToImage",
    description:
      "Convert code snippets into beautiful images with customizable themes and styles.",
    tags: ["TypeScript", "React.js", "Next.js", "Tailwind", "Vercel"],
    deployedUrl: "https://codetoimg-seven.vercel.app",
    githubUrl: "https://github.com/FALAK097/codetoimg",
    imageUrl: "/projects/codetoimg.png",
  },
];
