export const projects = [
  {
    id: "outcallerai",
    title: "OutCallerAI",
    description:
      "Automate inbound & outbound calls with ultra-realistic AI voices. Scale your outreach across any industry without extra manpower.",
    tags: [
      "Python",
      "OpenAI",
      "Gemini",
      "FastAPI",
      "TypeScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "Authjs",
      "Prisma",
      "PostgreSQL",
      "Redis",
      "Docker",
      "DigitalOcean",
      // "Plivo",
    ],
    deployedUrl: "https://outcallerai.com",
    imageUrl: "/projects/outcallerai.png",
  },
  {
    id: "glyph",
    title: "Glyph",
    description:
      "A local-first markdown editor and reader for macOS and Windows. Read local notes, edit markdown quickly, and keep everything on disk.",
    tags: [
      "Electron",
      "React.js",
      "TypeScript",
      "Tailwind",
    ],
    deployedUrl: "https://glyph.falakgala.dev",
    githubUrl: "https://github.com/FALAK097/glyph",
    imageUrl: "/projects/glyph.png",
  },
  {
    id: "waitlyze",
    title: "Waitlyze",
    description:
      "No-code platform to build waitlists, collect signups, and track analytics in real-time.",
    tags: [
      "Neon",
      "Docker",
      "Vercel",
      "BetterAuth",
      "JavaScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "Prisma",
      "PostgreSQL",
      // "Uploadthing",
    ],
    deployedUrl: "https://waitlyze.falakgala.dev",
    imageUrl: "/projects/waitlyze.png",
  },
  {
    id: "dms",
    title: "DMS",
    description:
      "Upload, search, and chat with your documents using AI. Automatic OCR, smart search, and seamless cloud syncing.",
    tags: [
      "JavaScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "BetterAuth",
      "Prisma",
      "OpenAI",
      "Gemini",
      "PostgreSQL",
      "Vercel",
      "Neon",
      "Upstash",
    ],
    deployedUrl: "https://dms.falakgala.dev",
    imageUrl: "/projects/dms.png",
  },
  {
    id: "typesteps",
    title: "TypeSteps",
    description:
      "A minimalist macOS app that passively tracks your daily typing activity and shows insights across days, weeks, and months.",
    tags: ["Swift"],
    githubUrl: "https://github.com/FALAK097/typesteps",
    imageUrl: "/projects/typesteps.png",
  },
  {
    id: "devfinder",
    title: "DevFinder",
    description:
      "Developer networking platform to connect, collaborate on projects, and share knowledge",
    tags: [
      "TypeScript",
      "React.js",
      "Next.js",
      "Tailwind",
      "Authjs",
      "Drizzle",
      "PostgreSQL",
      "Docker",
      // "Stream SDK",
    ],
    githubUrl: "https://github.com/FALAK097/devfinder",
    imageUrl: "/projects/devfinder.png",
  },
  {
    id: "spotify-clone",
    title: "Spotify Clone",
    description:
      "A full-stack music streaming web app replicating core Spotify features like playback, playlists, and user authentication.",
    tags: [
      "TypeScript",
      "React.js",
      "Next.js",
      "Tailwind CSS",
      "Supabase",
      "PostgreSQL",
      "Stripe",
      "Vercel",
    ],
    githubUrl: "https://github.com/FALAK097/spotify_clone",
    imageUrl: "/projects/spotify-clone.png",
  },
  {
    id: "github-scout",
    title: "Github Scout",
    description:
      "A GitHub profile viewer built with the MERN stack that displays user info, repositories, and followers.",
    tags: [
      "JavaScript",
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind",
      "GitHub",
    ],
    githubUrl: "https://github.com/FALAK097/github-scout",
    imageUrl: "/projects/mern-github.png",
  },
  {
    id: "codetoimage",
    title: "CodeToImage",
    description:
      "Convert code snippets into beautiful images with customizable themes and styles.",
    tags: ["TypeScript", "React.js", "Next.js", "Tailwind", "Vercel"],
    deployedUrl: "https://codetoimg-seven.vercel.app",
    githubUrl: "https://github.com/FALAK097/codetoimg",
    imageUrl: "/projects/codetoimg.png",
  },
];
