#!/usr/bin/env sh

echo '🏗️👷 Checking code quality before committing'

# Run lint-staged
pnpm lint-staged ||
(
    echo '😤 Prettier/ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false;
)

# If everything passes... Now we can commit
echo '✅ Code quality is good, committing now.'
